### ISSUE TITLE
Does this work with okta auth server ?

### ISSUE THREAD

**Issue by lquanx** [awslabs/fhir-works-on-aws-ui#26]
Hi,

We are using Okta auth server and smart-mainline branch of `fhir-works-on-aws-deployment`. I'm wondering if there is way to make it work with Okta auth server.

Thanks !

**Comment by nguyen102** [comment]
This web app doesn't currently support smart authentication. The web site uses the `/callback` url to store the access token received by the API server. The code for that is [here](https://github.com/awslabs/fhir-works-on-aws-ui/blob/mainline/src/components/callback/Callback.tsx)

If you go to the website at `/callback?id_token=<ACTUAL_TOKEN` and provide it with the actual auth server token, the UI will use that token for future API requests.
